categories: Categories
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
powered_by: Powered by
rss_feed: RSS
rss: RSS
category: Category
tag: Tag
friend_links: Friends
read_more: Read
home: Home
archives: Archives
about: About
search_placeholder: search this website...
author: Author
date: Published Date
update: Updated Date
post_categories: Categories
post_tags: Tags
post_licence: License
popular_post: Popular Posts

search:
  close: Close
  name: Search

state:
  posts: Blog
  categories: Categorie
  tags: Tag